export {AccordionList} from'@/features/AccordionList/AccordionList'
export {ContactForm} from'@/features/ContactForm/ContactForm'
export {Slider} from'@/features/Slider/Slider'
export {RatingList} from'@/features/RatingList/RatingList'
export {GpuTable} from'@/features/GpuTable/GpuTable'